# Generated by Django 5.2.6 on 2025-09-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, help_text="Définit si le produit est en vedette sur la page d'accueil"),
        ),
    ]
