# Generated by Django 5.2.6 on 2025-09-22 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du modèle')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Spécifications techniques au format JSON', verbose_name='Spécifications')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='products.brand', verbose_name='Marque')),
            ],
            options={
                'verbose_name': 'Modèle de produit',
                'verbose_name_plural': 'Modèles de produits',
                'ordering': ['brand__name', 'name'],
                'unique_together': {('name', 'brand')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productmodel', verbose_name='Modèle'),
        ),
    ]
