# Generated by Django 5.2.6 on 2025-09-23 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_products_pr_id_a08e3c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='specifications',
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_model', to='products.productmodel', verbose_name='Modèle'),
        ),
    ]
