# Generated by Django 5.2.6 on 2025-09-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_brand_remove_productmodel_is_active_and_more'),
    ]

    operations = [
    ]
