# Generated by Django 5.2.6 on 2025-09-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_brand_from_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_models/%Y/%m/%d/', verbose_name='Image du modèle'),
        ),
    ]
