# Generated by Django 5.2.6 on 2025-09-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productmodel_image'),
    ]

    operations = [
    ]
