# Generated by Django 5.2.6 on 2025-09-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_add_image_to_productmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default=1, upload_to='product_models/%Y/%m/%d/', verbose_name='Image du modèle'),
            preserve_default=False,
        ),
    ]
