# Generated by Django 5.2.6 on 2025-09-26 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='product_model', to='products.productmodel', verbose_name='Modèle'),
            preserve_default=False,
        ),
    ]
