# Generated by Django 5.2.7 on 2025-11-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['created_at'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_featured',
        ),
    ]
